name: argus
recipe: lamp
config:
  php: '8.1'
  database: mysql:8.0
  webroot: ./public/
tooling:
  dev:
    cmd:
      - appserver: cp example.env .env
      - appserver: composer install
      - database: mysql -u lamp -h database --password=lamp --execute="DROP DATABASE lamp;CREATE DATABASE lamp;"
      - database: mysql -u lamp -h database --password=lamp --database="lamp" < ./base.sql
  reset-db:
    cmd:
      - database: mysql -u lamp -h database --password=lamp --execute="DROP DATABASE lamp;CREATE DATABASE lamp;"
      - database: mysql -u lamp -h database --password=lamp --database="lamp" < ./base.sql
