version: '3'

services:
  web:
    image: ingrivera91/uacp:7.4-public
    ports:
      - "80:80"      
    volumes:
      - ./:/var/www/html
    links:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=argus
      - MYSQL_USER=user_argus
      - MYSQL_PASSWORD=pass_argus